//
// Code generated by gogen-enum DO NOT EDIT.
//
package config

import ()

// EventSourceType -- enum type
type EventSourceType int

// EventSourceType -- enum constants
const (
	EventSourceTypeUnknown EventSourceType = 0 + iota
	EventSourceTypeSQS
	EventSourceTypeSNS
	EventSourceTypeKinesis
)

// eventSourceType -- enum string representation constants
const (
	eventSourceTypeUnknown = "unknown"
	eventSourceTypeSQS     = "SQS"
	eventSourceTypeSNS     = "SNS"
	eventSourceTypeKinesis = "Kinesis"
)

// EventSourceTypeID -- map enum constant to string
var eventSourceTypeID = map[EventSourceType]string{
	EventSourceTypeUnknown: eventSourceTypeUnknown,
	EventSourceTypeSQS:     eventSourceTypeSQS,
	EventSourceTypeSNS:     eventSourceTypeSNS,
	EventSourceTypeKinesis: eventSourceTypeKinesis,
}

// EventSourceTypeName -- map string to enum constant
var eventSourceTypeName = map[string]EventSourceType{
	eventSourceTypeUnknown: EventSourceTypeUnknown,
	eventSourceTypeSQS:     EventSourceTypeSQS,
	eventSourceTypeSNS:     EventSourceTypeSNS,
	eventSourceTypeKinesis: EventSourceTypeKinesis,
}

// NewEventSourceType -- Create EventSourceType instance from string representation
func NewEventSourceType(k string) EventSourceType {
	if kind, ok := eventSourceTypeName[k]; ok {
		return kind
	}
	return EventSourceTypeUnknown
}

// String -- EventSourceType
func (t EventSourceType) String() string { return eventSourceTypeID[t] }
